isnts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'isnts'

handler404 = views.auth.error404


urlpatterns = [
    url(r'^donors/create_new/$', views.donor.create_new, name="donors"),
    url(r'^donors/(?P<donor_id>[0-9]+)/$', views.donor.detailview, name="donors"),
    url(r'^donors/(?P<donor_id>[0-9]+)/questionnaire/(?P<questionnaire_id>[0-9]+)/$', views.donor.quastionnaire, name="donors"),
    url(r'^donors/(?P<donor_id>[0-9]+)/blood_extraction/(?P<blood_extraction_id>[0-9]+)/$', views.donor.blood_extraction, name="donors"),
    url(r'^donors/information/$', views.donor.information, name="information"),
    url(r'^donors/terms/(?P<nts_id>[0-9]+)/$', views.donor.terms_choose_day, name="terms"),
    url(r'^donors/terms/$', views.donor.terms_choose_nts, name="terms"),
    url(r'^donors/terms/list/$', views.donor.terms_listview, name="my_terms"),
    url(r'^donors/terms/remove/(?P<booking_id>[0-9]+)/$', views.donor.terms_remove),
    url(r'^donors/$', views.donor.listview, name="donors"),
    url(r'^employees/(?P<employee_id>[0-9]+)/$', views.employee.detailview, name="employees"),
    url(r'^employees/$', views.employee.listview, name="employees"),
    url(r'^employees/login/$', views.auth.employee_login, name="employees"),
    url(r'^employees/officehours/$', views.employee.office_hours, name="office_hours"),
    url(r'^employees/register/$', views.auth.employee_register, name="employees"),
    url(r'^employees/interface/$', views.employee.interface, name="employees"),
    url(r'^employees/terms', views.employee.terms_list, name="terms"),
    url(r'^logout/$', views.auth._logout, name="employees"),
    url(r'^superuser/secret_key_change/$', views.superuser.secret_key_change, name="superuser_keychange"),
    url(r'^superuser/employee_administration/$', views.superuser.employee_administration, name="superuser_administration"),
    url(r'^superuser/employee_administration/(?P<employee_id>[0-9]+)/$', views.superuser.employee_activation, name="superuser_administration"),
    url(r'^blood_extraction/(?P<blood_extraction_id>[0-9]+)/$', views.blood_extraction.detailview, name="blood_extraction"),
    url(r'^blood_extraction/$', views.blood_extraction.listview, name="blood_extraction"),
    url(r'^login/$', views.auth.donor_login),
    url(r'^registration/confirm/(?P<donor_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.auth.donor_registration_confirm),
    url(r'^registration/$', views.auth.donor_registration),
    url(r'^password_change/$', views.auth.password_change),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.auth._password_reset_confirm),
    url(r'^password_reset/$', views.auth._password_reset),
    url(r'^password_reset_sent/$', views.auth.password_reset_sent),
    url(r'^nopermission/$', views.auth.permission_denied),
    url(r'^$', views.donor.home)
]

nts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from isnts import views
from django.conf.urls.static import static
from . import settings

handler404 = 'isnts.views.error404'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^health', views.auth.health),
    url(r'^',  include('isnts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

isnts/models.py
from django.db import models
from enum import Enum, unique
from django import forms
from django.contrib.auth.models import User
from .questions_enum import *
# Create your models here.


class BloodType(models.Model):

    @unique
    class Type(Enum):
        a = 0
        b = 1
        ab = 2
        o = 3

    TYPE_CHOICES = (
        (Type.a.value, "A"),
        (Type.b.value, "B"),
        (Type.ab.value, "AB"),
        (Type.o.value, "0")
    )

    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)

    @unique
    class RHFactor(Enum):
        plus = True
        minus = False

    RH_CHOICES = (
        (RHFactor.plus.value, "+"),
        (RHFactor.minus.value, "-")
    )
    RH = models.BooleanField(choices=RH_CHOICES)

    def __str__(self):
        return self.get_type_display() + self.get_RH_display()


class Region(models.Model):

    @unique
    class Regions(Enum):
        Bratislavsky = 0
        Nitriansky = 1
        Trnavsky = 2
        Trenciansky = 3
        BanskoBystricky = 4
        Zilinsky = 5
        Kosicky = 6
        Presovsky = 7

    REGION_CHOICES = (
        (Regions.Bratislavsky.value, "Bratislavsky"),
        (Regions.Nitriansky.value, "Nitriansky"),
        (Regions.Trnavsky.value, "Trnavsky"),
        (Regions.BanskoBystricky.value, "BanskoBystricky"),
        (Regions.Zilinsky.value, "Zilinsky"),
        (Regions.Kosicky.value, "Kosicky"),
        (Regions.Presovsky.value, "Presovsky"),
        (Regions.Trenciansky.value, "Trenciansky")
    )

    name = models.PositiveSmallIntegerField(choices=REGION_CHOICES)


class Town(models.Model):
    name = models.CharField(max_length=255)
    id_region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    town = models.ForeignKey(
        Town, on_delete=models.SET_NULL, null=True, blank=True)
    zip_code = models.CharField(max_length=10, null=True, blank=True)
    street = models.CharField(max_length=30, null=True, blank=True)
    number = models.CharField(max_length=10, null=True, blank=True)


class NTS(models.Model):
    name = models.CharField(max_length=30)
    id_address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True)
    location_info = models.CharField(max_length=50, null=True)
    gps_lon = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    gps_lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    other_contact = models.CharField(max_length=255)
    info = models.CharField(max_length=255)
    id_boss = models.IntegerField()
    secret_key = models.CharField(max_length=255, null=True)


class OfficeHours(models.Model):
    id_nts = models.ForeignKey(NTS, on_delete=models.CASCADE)
    DAYS_OF_WEEK = (
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday')
    )
    day = models.SmallIntegerField(choices=DAYS_OF_WEEK)
    open_time = models.TimeField(blank=True)
    close_time = models.TimeField(blank=True)


class Announcement(models.Model):
    id_nts = models.ForeignKey(NTS, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=50, null=True)
    text = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now_add=True)


class Employee(User):
    id_nts = models.ForeignKey(NTS, on_delete=models.CASCADE, null=True)
    phone = models.CharField(max_length=30, null=True)


class Donor(User):
    active_acount = models.BooleanField(default=False)
    email_verification_token = models.CharField(max_length=100, null=True)
    personal_identification_number = models.DecimalField(
        max_digits=20, decimal_places=0)

    @unique
    class Gender(Enum):
        male = 0
        female = 1

    GENDER_CHOICES = (
        (Gender.female.value, 'female'),
        (Gender.male.value, 'male')
    )

    gender = models.PositiveSmallIntegerField(
        choices=GENDER_CHOICES, default=0)

    class Meta:
        unique_together = ('personal_identification_number',)


class DonorCard(Donor):
    name = models.CharField(max_length=30, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    id_blood_type = models.ForeignKey(
        BloodType, on_delete=models.SET_NULL, null=True, blank=True)
    phone_num = models.CharField(max_length=20, blank=True)
    id_address_perm = models.ForeignKey(
        Address, on_delete=models.PROTECT, null=True, related_name="perm", blank=True)
    id_address_temp = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True, related_name="temp", blank=True)
    card_created_date = models.DateTimeField(auto_now_add=True, blank=True)
    card_created_by = models.ForeignKey(
        Employee, on_delete=models.SET_NULL, null=True, blank=True)
    info = models.CharField(max_length=255, null=True, blank=True)
    can_donate_from = models.DateField(null=True, blank=True)


class Questionnaire(models.Model):
    id_donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    weight = models.DecimalField(max_digits=6, decimal_places=2)
    height = models.DecimalField(max_digits=6, decimal_places=2)
    phone = models.CharField(max_length=20)
    created_address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True, related_name="created")
    created_date = models.DateTimeField(auto_now_add=True)


class Questions(models.Model):

    @unique
    class Answer(Enum):
        yes = 1
        no = 0
        not_sure = 2

    ANSWER_CHOICES = (
        (Answer.no.value, 'no'),
        (Answer.yes.value, 'yes'),
        (Answer.not_sure.value, 'not sure')
    )

    question = models.PositiveSmallIntegerField(choices=QUESTION_CHOICES)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    answer = models.PositiveSmallIntegerField(choices=ANSWER_CHOICES)
    additional_info = models.CharField(max_length=255, blank=True, null=True)
    employee_additional_info = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        unique_together = ('questionnaire', 'question')


class Booking(models.Model):
    id_nts = models.ForeignKey(NTS, on_delete=models.CASCADE)
    id_employee = models.ForeignKey(
        Employee, on_delete=models.SET_NULL, null=True)
    id_donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    booking_time = models.DateTimeField()
    id_answer_sheet = models.ForeignKey(
        Questionnaire, on_delete=models.SET_NULL, null=True)


class BloodExtraction(models.Model):

    @unique
    class State(Enum):
        new = 0
        ready_for_expedition = 1
        shipped = 2

    STATE_CHOICES = (
        (State.new.value, 'new'),
        (State.ready_for_expedition.value, 'ready for expedition'),
        (State.shipped.value, 'shipped')
    )

    state = models.PositiveSmallIntegerField(choices=STATE_CHOICES, default=0)
    blood_type = models.ForeignKey(BloodType, on_delete=models.CASCADE)
    barcode = models.CharField(max_length=255)
    id_donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    id_nts = models.ForeignKey(
        NTS, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    postpone = models.DateField(null=True, blank=True)
    note = models.CharField(max_length=255, blank=True)

isnts/views/blood_extraction.py
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.shortcuts import render
from isnts.models import *
from isnts.forms import *
from django.contrib import messages



def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


@login_required(login_url='/login/')
@permission_required('isnts.is_employee', login_url='/nopermission/')
def listview(request):
    samples_new = BloodExtraction.objects.filter(state=0)
    samples_ready_for_exp = BloodExtraction.objects.filter(state=1)
    samples_shipped = BloodExtraction.objects.filter(state=2)
    return render(request, 'blood_extraction/listview.html', {
        'samples_new': samples_new,
        'samples_ready_for_exp': samples_ready_for_exp,
        'samples_shipped': samples_shipped
    })


@login_required(login_url='/login/')
@permission_required('isnts.is_employee', login_url='/nopermission/')
def detailview(request, blood_extraction_id):
    blood_extraction = get_or_none(BloodExtraction, id=blood_extraction_id)
    blood_extraction_form = BloodExtractionForm(
        request.POST or None, instance=blood_extraction)
    if request.method == 'POST':
        if blood_extraction_form.is_valid():
            blood_extraction_form.save()
            messages.success(request, 'Blood extraction has been saved!')
        else:
            messages.success(request, 'Error! Please fill your form with valid values!')
    return render(request, 'blood_extraction/detailview.html', {'blood_extraction_form': blood_extraction_form})

isnts/views/superuser.py
from isnts.models import *
from isnts.forms import *
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib import messages
from django.contrib.auth.hashers import make_password


def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


@login_required(login_url='/employees/login/')
@permission_required('isnts.is_ntssu', login_url='/nopermission/')
def secret_key_change(request):
    secret_key_change_form = SecretKeyChange(request.POST or None)
    if request.method == 'POST':
        if secret_key_change_form.is_valid():
            employee = Employee.objects.get(id=request.user.id)
            data = secret_key_change_form.cleaned_data
            nts = employee.id_nts
            if data['secret_key_new'] == data['secret_key_new2']:
                nts.secret_key = make_password(data['secret_key_new2'])
                nts.save()
                messages.success(request, 'Secret key has been changed!')
            else:
                messages.success(
                    request, 'Error! Please fill your form with valid values!')

    return render(request, 'superuser/secret_key_change.html', {'form': secret_key_change_form})


@login_required(login_url='/employees/login/')
@permission_required('isnts.is_ntssu', login_url='/nopermission/')
def employee_administration(request):
    employees = Employee.objects.all()
    return render(request, 'superuser/employee_administration.html', {'employees': employees})


@login_required(login_url='/employees/login/')
@permission_required('isnts.is_ntssu', login_url='/nopermission/')
def employee_activation(request, employee_id):
    employees = Employee.objects.all()
    employee = get_or_none(Employee, id=employee_id)
    employee_activation_form = EmployeeActivationForm(request.POST or None)
    if request.method == 'POST':
        if employee_activation_form.is_valid():
            data = employee_activation_form.cleaned_data
            if data['activate'] == True:
                employee.is_active = True
                employee.save()
            else:
                employee.is_active = False
                employee.save()
            return HttpResponseRedirect('/superuser/employee_administration', {'employees': employees})
    return render(request, 'superuser/employee_administration_detailview.html', {'form': employee_activation_form, 'employee': employee})

isnts/templates/blood_extraction/detailview.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Blood sample{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <script>
                Materialize.toast('{{ message }}', 4000)
            </script>
        {% endfor %}
    {% endif %}
    <section>
        <br>
        <a href="/blood_extraction">Back</a>
        <h2 id="napisL">Blood sample</h2>
        <hr>
        <br><br>
        <form method="post" role="form">
            {% for field in blood_extraction_form.visible_fields %}
                <div id="div_{{ field.html_name }}"
                     class="form-group{% if field.errors %} has-error{% endif %} input-field">
                    {{ field }} {{ field.label_tag }}
                    <div class="help-block">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %} {% for hidden in blood_extraction_form.hidden_fields %}
            {{ hidden }} {% endfor %} {% csrf_token %}
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary"/>
            </div>
        </form>
    </section>
    <script type="text/javascript">
    $('.datepicker').pickadate({
      format: 'yyyy-mm-dd',
    });
    </script>
{% endblock %}

isnts/templates/blood_extraction/listview.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Blood samples{% endblock %} {% block content %}
<section>
    <h2 id="napisL">Blood extractions</h2>
    <hr>
    <div class="row">
        <div class="col s12">
            <ul class="tabs tabs-fixed-width">
                <li class="tab col s3"><a class="active" href="#test1">New samples</a></li>
                <li class="tab col s3"><a href="#test2">Ready for expedition</a></li>
                <li class="tab col s3"><a href="#test3">Shipped samples</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">
            <table class="responsive-table">
                <thead>
                    <tr>
                        <th data-field="id">Blood ID</th>
                        <th data-field="name">Donnor ID</th>
                        <th data-field="price">State</th>
                        <th data-field="price">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if samples_new %} {% for blood in samples_new %}
                    <tr class="picker__list-item--highlighted" onclick="window.location.href = '{{ blood.id }}';">
                        <td><span>{{ blood.id }}</span></td>
                        <td><span>{{ blood.id_donor }}</span></td>
                        <td><span>{{ blood.get_state_display }}</span></td>
                        <td><span>{{ blood.date }}</span></td>
                    </tr>
                    {% endfor %} {% else %}
                    <tr>
                        <td>There are no new blood samples for now</td>
                    </tr>
                    {% endif %}

                </tbody>
            </table>
        </div>
        <div id="test2" class="col s12">
            <table class="responsive-table">
                <thead>
                    <tr>
                        <th data-field="id">Blood ID</th>
                        <th data-field="name">Donnor ID</th>
                        <th data-field="price">State</th>
                        <th data-field="price">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if samples_ready_for_exp %} {% for blood in samples_ready_for_exp %}
                    <tr class="picker__list-item--highlighted" onclick="window.location.href = '{{ blood.id }}';">
                        <td><span>{{ blood.id }}</span></td>
                        <td><span>{{ blood.id_donor }}</span></td>
                        <td><span>{{ blood.get_state_display }}</span></td>
                        <td><span>{{ blood.date }}</span></td>
                    </tr>
                    {% endfor %} {% else %}
                    <tr>
                        <td>There are no ready blood samples for now</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div id="test3" class="col s12">
            <table class="responsive-table">
                <thead>
                    <tr>
                        <th data-field="id">Blood ID</th>
                        <th data-field="name">Donnor ID</th>
                        <th data-field="price">State</th>
                        <th data-field="price">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if samples_shipped %} {% for blood in samples_shipped %}
                    <tr class="picker__list-item--highlighted" onclick="window.location.href = '{{ blood.id }}';">
                        <td><span>{{ blood.id }}</span></td>
                        <td><span>{{ blood.id_donor }}</span></td>
                        <td><span>{{ blood.get_state_display }}</span></td>
                        <td><span>{{ blood.date }}</span></td>
                    </tr>
                    {% endfor %} {% else %}
                    <tr>
                        <td>There are no blood samples for now</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

</section>
{% endblock %}